{
 "title": "LokiGO Dashboard",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uuid",
    "label": "uuid",
    "query": "label_values({uuid=~\".+\"}, uuid)"
   },
   {
    "name": "product",
    "label": "product",
    "query": "label_values({product=~\".+\"}, product)"
   },
   {
    "name": "logtype",
    "label": "logtype",
    "query": "label_values({logtype=~\".+\"}, logtype)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   {
    "name": "ignore_filter",
    "label": "Ignore filter (case insensitive)",
    "query": "^$"
   }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of  $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$ignore_filter\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Product distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\"})[$__interval])) by (product)"
    }
   ]
  },
  {
   "title": "Product distribution with $searchable_pattern",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\"})|~ \"(?i)$searchable_pattern\"!~ \"(?i)$ignore_filter\"[$__interval])) by (product)"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)critical\")[$__interval]))",
     "legendFormat": "critical"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)error\")[$__interval]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)warning\")[$__interval]))",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)unusual\")[$__interval]))",
     "legendFormat": "unusual"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)info\")[$__interval]))",
     "legendFormat": "info"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)trace\")[$__interval]))",
     "legendFormat": "trace"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)debug\")[$__interval]))",
     "legendFormat": "debug"
    },
    {
     "expr": "sum(count_over_time(({uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"})[$__interval]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Consolidated Logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{uuid=\"$uuid\", product=~\"$product\", logtype=~\"$logtype\"} |~ \"(?i)$searchable_pattern\" !~ \"(?i)$ignore_filter\""
    }
   ]
  }
 ]
}