server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
- job_name: staros_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: staros_log
      product: 'staros'
      logtype: 'logging'
      __path__: /var/log/staros_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[0-9]{4}-[a-zA-Z]{3}-[0-9]{2}\+[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---2006-Jan-02+15:04:05.000'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: staros_trap
  static_configs:
  - targets:
      - localhost
    labels:
      job: staros_trap
      product: 'staros'
      logtype: 'trap'
      __path__: /var/log/staros_trap/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[a-zA-Z]{3} [0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} [0-9]{4}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---Jan 02 15:04:05 2006'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: staros_debug
  static_configs:
  - targets:
      - localhost
    labels:
      job: staros_debug
      product: 'staros'
      logtype: 'debug'
      __path__: /var/log/staros_dbgc*/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[0-9]{4}-[a-zA-Z]{3}-[0-9]{2}\+[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
      time:
  - timestamp:
      source: time
      format: '-0700 ---2006-Jan-02+15:04:05.000'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: cvim_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: cvim_log
      product: 'cvim'
      logtype: 'logging'
      __path__: /var/log/cvim_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[0-9]{4} [a-zA-Z]{3}.*[0-9]{1,2} [0-9]{2}:[0-9]{2}:[0-9]{2}) [a-zA-Z0-9-_]+ (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---2006 Jan _2 15:04:05'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: ucs_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: ucs_log
      product: 'ucs'
      logtype: 'logging'
      __path__: /var/log/ucs_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[0-9]{4}-[a-zA-Z]{3}-[0-9]{2}\+[0-9]{2}:[0-9]{2}:[0-9]{2}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---2006-Jan-2+15:04:05'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: nxos_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: nxos_log
      product: 'nxos'
      logtype: 'logging'
      __path__: /var/log/nxos_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>-|\+[0-9]{4} ---[0-9]{4} [a-zA-Z]{3} [0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---2006 Jan 2 15:04:05'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .message }}'
  - output:
      source: output_msg

- job_name: xr_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: xr_log
      product: 'ios_xr'
      logtype: 'logging'
      __path__: /var/log/ios_xr_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- [A-Z]{3} ---(?P<time>[0-9]{4} [a-zA-Z]{3} [0-9]{1,2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3} [-|\+][0-9]{4})  (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '2006 Jan _2 15:04:05.000 -0700'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg

- job_name: iosxe_log
  static_configs:
  - targets:
      - localhost
    labels:
      job: iosxe_log
      product: 'iosxe'
      logtype: 'logging'
      __path__: /var/log/iosxe_log/*log
  pipeline_stages:
  - regex:
      expression: ^(?P<uuid>.*)---(?P<hostname>.*)--- (?P<time>(?:-|\+)[0-9]{4} ---[0-9]{4} [a-zA-Z]{3}.*[0-9]{1,2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}) (?P<message>.*$)
  - labels:
      hostname:
      uuid:
  - timestamp:
      source: time
      format: '-0700 ---2006 Jan _2 15:04:05.000'
  - template:
      source: output_msg
      template: '{{ .product }} {{ .hostname }} {{ .message }}'
  - output:
      source: output_msg
